import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
df=pd.read_csv(r'C:\Users\21Lab\Data.csv')
print(df)
print("\nDescription of dataframe")
print(df.describe())
print("\nShape of Dataframe")
print(df.shape)
print("\nfirst 3 Roes of data set")
print(df.head(3))
print("\nMisinng values")
x=df['Age'].mean()
df['Age'].fillna(x,inplace=True)
x1=df['Salary'].mean()
df['Salary'].fillna(x1,inplace=True)
print(df)
print("\n One HoT Enocder")
enc=OneHotEncoder(handle_unknown='ignore')
enc_df=pd.DataFrame(enc.fit_transform(df[['Country']]).toarray())
df=df.join(enc_df)
print(df)
print("\n Label Encoding")
labelencoder=LabelEncoder()
df['Purchased']=labelencoder.fit_transform(df['Purchased'])
print(df)
