a=int(input("Enter the first number: "));
b=int(input("Enter the second number: "));
add=a=b;
sub=a-b;
mul=a*b;
div=a/b;
print("Addition=",add);
print("Subtract=",sub);
print("multiplication=",mul);
print("Division=",div);